# Generated by Django 5.2.9 on 2026-01-24 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_message_receiver_alter_message_sender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
